- hosts: sample
  gather_facts: yes
  become: True

  roles:
    - hostname
    - timezone
    - users/add_admin
    - packages/update
    - packages/usefuls
    - packages/usefuls/private
    - samba
